# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

parameters:
  os:
    type: string
    default: "ubuntu-22.04"
  mode:
    type: string
    default: "newlib"
  compiler:
    type: string
    default: "gcc"

jobs:
  build-ubuntu-22_04:
    machine:
      image: ubuntu-2204:current
      resource_class: large
    steps:
      - checkout
      - run:
          name: Checkout required submodules
          command: git submodule update --init -j $(nproc) --depth 1 binutils gcc gdb glibc musl newlib pk qemu spike uclibc-ng
      - run:
          name: Storage size optimization
          command: git submodule foreach 'git maintenance run'
      - run:
          name: Setup swap space
          command: |
            sudo fallocate -l 80G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
      - run:
          name: install dependencies
          command: sudo -E .github/setup-apt.sh
      - run:
          name: build toolchain
          command: |
            ./configure --prefix=/mnt/riscv --enable-multilib
            sudo mkdir /mnt/riscv
            sudo chown $(whoami):$(whoami) /mnt/riscv
            make -j $(nproc)
      - run:
          name: tarball build
          command: |
            du -s -h /mnt/riscv
            .github/dedup-dir.sh /mnt/riscv/
            TOOLCHAIN_NAME="riscv-elf-ubuntu-22.04-gcc-nightly"
            XZ_OPT="-e -T0" tar cJvf ${TOOLCHAIN_NAME}.tar.xz -C /mnt/ riscv/
      - store_artifacts:
          path: riscv-elf-ubuntu-22.04-gcc-nightly.tar.xz
          destination: toolchain-tarball

  build-ubuntu-24_04:
    machine:
      image: ubuntu-2404:current
      resource_class: large
    steps:
      - checkout
      - run:
          name: Checkout required submodules
          command: git submodule update --init -j $(nproc) --depth 1 binutils gcc gdb glibc musl newlib pk qemu spike uclibc-ng
      - run:
          name: Storage size optimization
          command: git submodule foreach 'git maintenance run'
      - run:
          name: Setup swap space
          command: |
            sudo fallocate -l 80G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
      - run:
          name: install dependencies
          command: sudo -E .github/setup-apt.sh
      - run:
          name: build toolchain
          command: |
            ./configure --prefix=/mnt/riscv --enable-multilib
            sudo mkdir /mnt/riscv
            sudo chown $(whoami):$(whoami) /mnt/riscv
            make -j $(nproc)
      - run:
          name: tarball build
          command: |
            du -s -h /mnt/riscv
            .github/dedup-dir.sh /mnt/riscv/
            TOOLCHAIN_NAME="riscv-elf-ubuntu-24.04-gcc-nightly"
            XZ_OPT="-e -T0" tar cJvf ${TOOLCHAIN_NAME}.tar.xz -C /mnt/ riscv/
      - store_artifacts:
          path: riscv-elf-ubuntu-24.04-gcc-nightly.tar.xz
          destination: toolchain-tarball
      - run:
          name: make report
          command: |
            make report-newlib -j $(nproc)

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-ubuntu-22_04
      - build-ubuntu-24_04